version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillbox_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_logs:/var/log/postgresql
    networks:
      - flask_net
    command: >
      postgres -c log_destination=stderr
               -c logging_collector=on
               -c log_directory=/var/log/postgresql

  web:
    build: .
    container_name: flask_app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app.main:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/skillbox_db
    depends_on:
      - db
    networks:
      - flask_net

volumes:
  pg_data:

networks:
  flask_net:
    driver: bridge